package com.potato.unicornpotato.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USERS".
 */
@Entity
public class Users {

    @Id
    private Long id;

    @NotNull
    private String Firstname;
    private String Email;
    private String Password;
    private java.util.Date Lastname;

    @Generated
    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    @Generated
    public Users(Long id, String Firstname, String Email, String Password, java.util.Date Lastname) {
        this.id = id;
        this.Firstname = Firstname;
        this.Email = Email;
        this.Password = Password;
        this.Lastname = Lastname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getFirstname() {
        return Firstname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstname(@NotNull String Firstname) {
        this.Firstname = Firstname;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public java.util.Date getLastname() {
        return Lastname;
    }

    public void setLastname(java.util.Date Lastname) {
        this.Lastname = Lastname;
    }

}
